trigger:
  - '*'

pool:
  name: Default

variables:
  buildConfiguration: 'Release'  # Release or Debug
  wwwRootDir: 'Tailspin.SpaceGame.Web/wwwroot'

steps:
  - task: UseDotNet@2
    displayName: 'Use .Net SDK'
    inputs:
      packageType: sdk
      version: '6.x'

  - task: Npm@1
    displayName: 'run npm install'
    inputs:
      verbose: false

  - bash: ./node_modules/.bin/node-sass $(wwwRootDir) --output $(wwwRootDir)
    displayName: 'Compile Sass assets'

  - task: gulp@1
    displayName: 'Run gulp tasks'

  - bash: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: 'Write build info'
    workingDirectory: $(wwwRootDir)

  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - template: templates/build.yaml
    parameters:
      buildConfiguration: Debug

  - template: templates/build.yaml
    parameters:
      buildConfiguration: Release

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeeded()
